//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentCockpit.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using DeploymentCockpit.Models;
    
    public partial class DeploymentCockpitEntities : DbContext
    {
        public DeploymentCockpitEntities()
            : base("name=DeploymentCockpitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Credential> Credentials { get; set; }
        public virtual DbSet<Script> Scripts { get; set; }
        public virtual DbSet<Target> Targets { get; set; }
        public virtual DbSet<TargetGroup> TargetGroups { get; set; }
        public virtual DbSet<ProjectEnvironment> ProjectEnvironments { get; set; }
        public virtual DbSet<ProjectTarget> ProjectTargets { get; set; }
        public virtual DbSet<DeploymentPlan> DeploymentPlans { get; set; }
        public virtual DbSet<DeploymentPlanStep> DeploymentPlanSteps { get; set; }
        public virtual DbSet<DeploymentJob> DeploymentJobs { get; set; }
        public virtual DbSet<ScriptParameter> ScriptParameters { get; set; }
        public virtual DbSet<Variable> Variables { get; set; }
        public virtual DbSet<DeploymentJobStep> DeploymentJobSteps { get; set; }
        public virtual DbSet<DeploymentJobStepTarget> DeploymentJobStepTargets { get; set; }
    }
}
