//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentCockpit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeploymentPlanParameter
    {
        public int DeploymentPlanParameterID { get; set; }
        public short DeploymentPlanID { get; set; }
        public string Name { get; set; }
    
        public virtual DeploymentPlan DeploymentPlan { get; set; }
    }
}
