//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentCockpit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeploymentJob
    {
        public DeploymentJob()
        {
            this.DeploymentJobSteps = new HashSet<DeploymentJobStep>();
        }
    
        public int DeploymentJobID { get; set; }
        public short ProjectID { get; set; }
        public System.DateTime SubmissionTime { get; set; }
        public string SubmittedBy { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string StatusKey { get; set; }
        public string ProductVersion { get; set; }
        public short ProjectEnvironmentID { get; set; }
        public short DeploymentPlanID { get; set; }
        public string Notes { get; set; }
        public string Errors { get; set; }
    
        public virtual DeploymentPlan DeploymentPlan { get; set; }
        public virtual Project Project { get; set; }
        public virtual ProjectEnvironment ProjectEnvironment { get; set; }
        public virtual ICollection<DeploymentJobStep> DeploymentJobSteps { get; set; }
    }
}
