//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentCockpit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeploymentPlanStep
    {
        public DeploymentPlanStep()
        {
            this.DeploymentJobSteps = new HashSet<DeploymentJobStep>();
        }
    
        public int DeploymentPlanStepID { get; set; }
        public short DeploymentPlanID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public short ExecutionOrder { get; set; }
        public short ScriptID { get; set; }
        public bool AllTargetGroups { get; set; }
        public Nullable<short> TargetGroupID { get; set; }
        public bool RemoteExecution { get; set; }
    
        public virtual DeploymentPlan DeploymentPlan { get; set; }
        public virtual Script Script { get; set; }
        public virtual TargetGroup TargetGroup { get; set; }
        public virtual ICollection<DeploymentJobStep> DeploymentJobSteps { get; set; }
    }
}
