//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentCockpit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Scripts = new HashSet<Script>();
            this.TargetGroups = new HashSet<TargetGroup>();
            this.Environments = new HashSet<ProjectEnvironment>();
            this.DeploymentPlans = new HashSet<DeploymentPlan>();
            this.DeploymentJobs = new HashSet<DeploymentJob>();
            this.DeploymentJobParameters = new HashSet<DeploymentJobParameter>();
        }
    
        public short ProjectID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Script> Scripts { get; set; }
        public virtual ICollection<TargetGroup> TargetGroups { get; set; }
        public virtual ICollection<ProjectEnvironment> Environments { get; set; }
        public virtual ICollection<DeploymentPlan> DeploymentPlans { get; set; }
        public virtual ICollection<DeploymentJob> DeploymentJobs { get; set; }
        public virtual ICollection<DeploymentJobParameter> DeploymentJobParameters { get; set; }
    }
}
