//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentCockpit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Script
    {
        public Script()
        {
            this.DeploymentPlanSteps = new HashSet<DeploymentPlanStep>();
            this.Parameters = new HashSet<ScriptParameter>();
        }
    
        public short ScriptID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ScriptType { get; set; }
        public string Body { get; set; }
        public string SuccessKeywords { get; set; }
        public string FailureKeywords { get; set; }
        public Nullable<short> ProjectID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<DeploymentPlanStep> DeploymentPlanSteps { get; set; }
        public virtual ICollection<ScriptParameter> Parameters { get; set; }
    }
}
