//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentCockpit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptParameter
    {
        public int ScriptParameterID { get; set; }
        public short ScriptID { get; set; }
        public string Name { get; set; }
        public string DefaultValue { get; set; }
        public bool IsMandatory { get; set; }
    
        public virtual Script Script { get; set; }
    }
}
