//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentCockpit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Target
    {
        public Target()
        {
            this.ProjectTargets = new HashSet<ProjectTarget>();
            this.DeploymentJobStepTargets = new HashSet<DeploymentJobStepTarget>();
        }
    
        public short TargetID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ComputerName { get; set; }
        public int PortNumber { get; set; }
        public string TargetKey { get; set; }
        public short CredentialID { get; set; }
    
        public virtual Credential Credential { get; set; }
        public virtual ICollection<ProjectTarget> ProjectTargets { get; set; }
        public virtual ICollection<DeploymentJobStepTarget> DeploymentJobStepTargets { get; set; }
    }
}
