//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentCockpit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variable
    {
        public int VariableID { get; set; }
        public string ScopeKey { get; set; }
        public int ScopeID { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    }
}
